CREATE TABLE IF NOT EXISTS api_source_config (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    url_template VARCHAR(255),
    enabled BOOLEAN,
    timeout_ms INTEGER,
    last_checked TIMESTAMP
);

CREATE TABLE IF NOT EXISTS currency_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency VARCHAR(255),
    rate DECIMAL(19,4),
    base_currency VARCHAR(255),
    rate_date TIMESTAMP,
    source_id VARCHAR(255),
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_currency_rate_date ON currency_rate (currency, rate_date);

CREATE TABLE IF NOT EXISTS raw_api_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(255),
    received_at TIMESTAMP,
    payload CLOB,
    status VARCHAR(255),
    attempts INTEGER,
    last_error VARCHAR(255),
    version BIGINT
);
